/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class util_JTdoa */

#ifndef _Included_util_JTdoa
#define _Included_util_JTdoa
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     util_JTdoa
 * Method:    TDOACreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_util_JTdoa_TDOACreate
  (JNIEnv *, jobject);

/*
 * Class:     util_JTdoa
 * Method:    TDOAVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_util_JTdoa_TDOAVersion
  (JNIEnv *, jobject);

/*
 * Class:     util_JTdoa
 * Method:    TDOABindUserData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_util_JTdoa_TDOABindUserData
  (JNIEnv *, jobject);

/*
 * Class:     util_JTdoa
 * Method:    TDOAUserData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_util_JTdoa_TDOAUserData
  (JNIEnv *, jobject);

/*
 * Class:     util_JTdoa
 * Method:    TDOADestory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_util_JTdoa_TDOADestory
  (JNIEnv *, jobject);

/*
 * Class:     util_JTdoa
 * Method:    TDOADisconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_util_JTdoa_TDOADisconnect
  (JNIEnv *, jobject);

/*
 * Class:     util_JTdoa
 * Method:    TDOASetCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_util_JTdoa_TDOASetCallback
  (JNIEnv *, jobject);

/*
 * Class:     util_JTdoa
 * Method:    TDOAConnect
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOAConnect
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     util_JTdoa
 * Method:    TDOAConnectUpdate
 * Signature: (Ljava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOAConnectUpdate
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     util_JTdoa
 * Method:    TDOALoginServer
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOALoginServer
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jstring);

/*
 * Class:     util_JTdoa
 * Method:    TDOACreateUser
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOACreateUser
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     util_JTdoa
 * Method:    TDOAUpdatePassword
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOAUpdatePassword
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     util_JTdoa
 * Method:    TDOAReqPortfolio
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOAReqPortfolio
  (JNIEnv *, jobject);

/*
 * Class:     util_JTdoa
 * Method:    TDOAReqAccountState
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOAReqAccountState
  (JNIEnv *, jobject, jlong);

/*
 * Class:     util_JTdoa
 * Method:    TDOAGetOrderId
 * Signature: (IJI)V
 */
JNIEXPORT void JNICALL Java_util_JTdoa_TDOAGetOrderId
  (JNIEnv *, jobject, jint, jlong, jint);

/*
 * Class:     util_JTdoa
 * Method:    TDOAPlaceOrder
 * Signature: (JLutil/Contract;Lutil/Order;)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOAPlaceOrder
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     util_JTdoa
 * Method:    TDOABachOrder
 * Signature: (Lutil/OrderCombination;I)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOABachOrder
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     util_JTdoa
 * Method:    TDOACancelOrder
 * Signature: (JJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOACancelOrder
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     util_JTdoa
 * Method:    TDOABachCancelOrder
 * Signature: (Lutil/CancelOrderData;I)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOABachCancelOrder
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     util_JTdoa
 * Method:    TDOASubscribeOrderState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOASubscribeOrderState
  (JNIEnv *, jobject);

/*
 * Class:     util_JTdoa
 * Method:    TDOASubscribeMarketDepth
 * Signature: (JLutil/Contract;I)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOASubscribeMarketDepth
  (JNIEnv *, jobject, jlong, jobject, jint);

/*
 * Class:     util_JTdoa
 * Method:    TDOASubscibeLevel1Data
 * Signature: (JLutil/Contract;)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOASubscibeLevel1Data
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     util_JTdoa
 * Method:    TDOASubscribeMarketData
 * Signature: (JLutil/Contract;)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOASubscribeMarketData
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     util_JTdoa
 * Method:    TDOASubscribeNews
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOASubscribeNews
  (JNIEnv *, jobject, jlong);

/*
 * Class:     util_JTdoa
 * Method:    TDOACancelMarketDepth
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOACancelMarketDepth
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     util_JTdoa
 * Method:    TDOACancelLevel1Data
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOACancelLevel1Data
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     util_JTdoa
 * Method:    TDOACancelMarketData
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOACancelMarketData
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     util_JTdoa
 * Method:    TDOAReqHistoryPlacedOrder
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOAReqHistoryPlacedOrder
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     util_JTdoa
 * Method:    TDOAReqHistoryFilledOrder
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOAReqHistoryFilledOrder
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     util_JTdoa
 * Method:    TDOAReqDayPlacedOrder
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOAReqDayPlacedOrder
  (JNIEnv *, jobject, jlong);

/*
 * Class:     util_JTdoa
 * Method:    TDOAReqDayFilledOrder
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOAReqDayFilledOrder
  (JNIEnv *, jobject, jlong);

/*
 * Class:     util_JTdoa
 * Method:    TDOAReqDeliveryOrder
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOAReqDeliveryOrder
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     util_JTdoa
 * Method:    TDOAReqRQPos
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOAReqRQPos
  (JNIEnv *, jobject, jlong);

/*
 * Class:     util_JTdoa
 * Method:    TDOAReqRiskParam
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOAReqRiskParam
  (JNIEnv *, jobject);

/*
 * Class:     util_JTdoa
 * Method:    TDOAReqFee
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOAReqFee
  (JNIEnv *, jobject);

/*
 * Class:     util_JTdoa
 * Method:    TDOAReqSymbolQuery
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOAReqSymbolQuery
  (JNIEnv *, jobject, jlong);

/*
 * Class:     util_JTdoa
 * Method:    TDOATimerFunction
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOATimerFunction
  (JNIEnv *, jobject);

/*
 * Class:     util_JTdoa
 * Method:    TDOARecvMessage
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOARecvMessage
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     util_JTdoa
 * Method:    TDOAReqProfitList
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_util_JTdoa_TDOAReqProfitList
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
